name: Deploy Discord and Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean up old installations
      run: |
        python -m pip uninstall -y discord.py python-telegram-bot
        python -m pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check installed packages
      run: |
        python -m pip list

    - name: Verify Python paths
      run: |
        python -m site

    - name: Run main.py
      run: |
        python main.py | tee bot_logs.txt

    - name: Run id.py
      run: |
        python id.py | tee bot_logs.txt

    - name: Notify Discord - Send bot logs
      if: always()
      run: |
        LOG_CONTENT=$(cat bot_logs.txt)
        LOG_CONTENT_CUT=$(echo "$LOG_CONTENT" | tail -n 20) # To keep the logs concise
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"embeds\": [{\"title\": \"Bot logs\", \"description\": \"\`\`\`$LOG_CONTENT_CUT\`\`\`\", \"color\": 16753920}]}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord - Workflow completed
      if: always()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"embeds\": [{\"title\": \"Workflow completed\", \"description\": \"Workflow completed for $GITHUB_REPOSITORY on $GITHUB_REF\", \"color\": 3066993}]}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord - Failure
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"embeds\": [{\"title\": \"Workflow failed\", \"description\": \"Workflow failed for $GITHUB_REPOSITORY on $GITHUB_REF\", \"color\": 15158332}]}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
